import { execSync } from 'child_process';
import { existsSync, writeFileSync, readFileSync } from 'fs';
import { join, resolve } from 'path';

const OPENAPI_URL = process.env.OPENAPI_URL ?? 'http://localhost:8000/openapi.json';
const LOCAL_PATH = resolve(__dirname, '../../kyros-backend/openapi.json');
const OUT_PATH = resolve(__dirname, '../src/api/generated/schema.ts');

async function main() {
  let schemaContent: string;

  if (existsSync(LOCAL_PATH)) {
    console.log(`Reading schema from local path: ${LOCAL_PATH}`);
    schemaContent = readFileSync(LOCAL_PATH, 'utf-8');
  } else {
    console.log(`Fetching schema from: ${OPENAPI_URL}`);
    const res = await fetch(OPENAPI_URL);
    if (!res.ok) throw new Error(`HTTP ${res.status}: ${await res.text()}`);
    schemaContent = await res.text();
  }

  // Write to a temp file
  const tmpPath = join('/tmp', 'openapi_schema.json');
  writeFileSync(tmpPath, schemaContent);

  // Run openapi-typescript
  console.log('Running openapi-typescript...');
  const raw = execSync(
    `npx openapi-typescript ${tmpPath} --output -`,
    { encoding: 'utf-8', maxBuffer: 10 * 1024 * 1024 }
  );

  const banner = `// This file is auto-generated by scripts/sync-types.ts
// Run \`pnpm sync:types\` to regenerate after backend changes
// Last generated: ${new Date().toISOString()}
// DO NOT EDIT MANUALLY

`;

  writeFileSync(OUT_PATH, banner + raw);
  console.log(`Types written to: ${OUT_PATH}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
